<?php

/**
 * Company
 *
 * PHP version 8.1
 *
 * @category Class
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Credit Online API
 *
 * A Token hívás segítségével generált egyedi tokennel hívható a többi metódus. Az egyes funkciók a dokumentációban a \"Try it out\" gomb megnyomásával online is kipróbálhatóak.
 *
 * The version of the OpenAPI document: 3
 * Contact: antolik.laszlo@creditcontrol.hu
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Omisai\CreditOnline\Model;

use ArrayAccess;
use Omisai\CreditOnline\ObjectSerializer;
use Omisai\CreditOnline\Model\Address;
use Omisai\CreditOnline\Model\Auditor;
use Omisai\CreditOnline\Model\FinancialSummary;
use Omisai\CreditOnline\Model\Member;
use Omisai\CreditOnline\Model\NegativeInfo;
use Omisai\CreditOnline\Model\PositiveInfo;
use Omisai\CreditOnline\Model\Signer;

/**
 * Company Class Doc Comment
 *
 * @category Class
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class Company implements \JsonSerializable, ArrayAccess, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Company';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'regnumber' => 'string',
        'taxnumber' => 'string',
        'name' => 'string',
        'long_name' => 'string',
        'headquarter' => '\Omisai\CreditOnline\Model\Address',
        'status' => 'string',
        'foundation' => '\DateTime',
        'funds' => 'string',
        'employees' => 'int',
        'last_turnover' => 'int',
        'main_activity_code' => 'string',
        'main_activity_description' => 'string',
        'rating' => 'int',
        'credit_limit' => 'int',
        'industry' => 'string',
        'type' => 'string',
        'ksh_number' => 'string',
        'eu_taxnumber' => 'string',
        'link' => 'string',
        'bank_accounts' => 'string[]',
        'phones' => 'string[]',
        'emails' => 'string[]',
        'webpages' => 'string[]',
        'negative_info' => '\Omisai\CreditOnline\Model\NegativeInfo[]',
        'positive_info' => '\Omisai\CreditOnline\Model\PositiveInfo[]',
        'financial_summaries' => '\Omisai\CreditOnline\Model\FinancialSummary[]',
        'signers' => '\Omisai\CreditOnline\Model\Signer[]',
        'members' => '\Omisai\CreditOnline\Model\Member[]',
        'auditors' => '\Omisai\CreditOnline\Model\Auditor[]',
        'sites' => '\Omisai\CreditOnline\Model\Address[]',
        'has_deleted_tax_number' => 'bool',
        'has_active_positive_info' => 'bool',
        'has_active_negative_info' => 'bool',
        'is_koztartozasmentes' => 'bool',
        'is_megbizhato_adozo' => 'bool',
        'has_prohibited_member' => 'bool',
        'signer_change_in12_months' => 'bool',
        'member_change_in12_months' => 'bool',
        'headquarter_change_in12_months' => 'bool',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'regnumber' => null,
        'taxnumber' => null,
        'name' => null,
        'long_name' => null,
        'headquarter' => null,
        'status' => null,
        'foundation' => 'date',
        'funds' => null,
        'employees' => null,
        'last_turnover' => null,
        'main_activity_code' => null,
        'main_activity_description' => null,
        'rating' => null,
        'credit_limit' => null,
        'industry' => null,
        'type' => null,
        'ksh_number' => null,
        'eu_taxnumber' => null,
        'link' => null,
        'bank_accounts' => null,
        'phones' => null,
        'emails' => null,
        'webpages' => null,
        'negative_info' => null,
        'positive_info' => null,
        'financial_summaries' => null,
        'signers' => null,
        'members' => null,
        'auditors' => null,
        'sites' => null,
        'has_deleted_tax_number' => null,
        'has_active_positive_info' => null,
        'has_active_negative_info' => null,
        'is_koztartozasmentes' => null,
        'is_megbizhato_adozo' => null,
        'has_prohibited_member' => null,
        'signer_change_in12_months' => null,
        'member_change_in12_months' => null,
        'headquarter_change_in12_months' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'regnumber' => false,
        'taxnumber' => false,
        'name' => false,
        'long_name' => false,
        'headquarter' => false,
        'status' => false,
        'foundation' => false,
        'funds' => false,
        'employees' => false,
        'last_turnover' => false,
        'main_activity_code' => false,
        'main_activity_description' => false,
        'rating' => false,
        'credit_limit' => false,
        'industry' => false,
        'type' => false,
        'ksh_number' => false,
        'eu_taxnumber' => false,
        'link' => false,
        'bank_accounts' => false,
        'phones' => false,
        'emails' => false,
        'webpages' => false,
        'negative_info' => false,
        'positive_info' => false,
        'financial_summaries' => false,
        'signers' => false,
        'members' => false,
        'auditors' => false,
        'sites' => false,
        'has_deleted_tax_number' => false,
        'has_active_positive_info' => false,
        'has_active_negative_info' => false,
        'is_koztartozasmentes' => false,
        'is_megbizhato_adozo' => false,
        'has_prohibited_member' => false,
        'signer_change_in12_months' => false,
        'member_change_in12_months' => false,
        'headquarter_change_in12_months' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param  bool[]  $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'regnumber' => 'Regnumber',
        'taxnumber' => 'Taxnumber',
        'name' => 'Name',
        'long_name' => 'LongName',
        'headquarter' => 'Headquarter',
        'status' => 'Status',
        'foundation' => 'Foundation',
        'funds' => 'Funds',
        'employees' => 'Employees',
        'last_turnover' => 'LastTurnover',
        'main_activity_code' => 'MainActivityCode',
        'main_activity_description' => 'MainActivityDescription',
        'rating' => 'Rating',
        'credit_limit' => 'CreditLimit',
        'industry' => 'Industry',
        'type' => 'Type',
        'ksh_number' => 'KSHNumber',
        'eu_taxnumber' => 'EUTaxnumber',
        'link' => 'Link',
        'bank_accounts' => 'BankAccounts',
        'phones' => 'Phones',
        'emails' => 'Emails',
        'webpages' => 'Webpages',
        'negative_info' => 'NegativeInfo',
        'positive_info' => 'PositiveInfo',
        'financial_summaries' => 'FinancialSummaries',
        'signers' => 'Signers',
        'members' => 'Members',
        'auditors' => 'Auditors',
        'sites' => 'Sites',
        'has_deleted_tax_number' => 'HasDeletedTaxNumber',
        'has_active_positive_info' => 'HasActivePositiveInfo',
        'has_active_negative_info' => 'HasActiveNegativeInfo',
        'is_koztartozasmentes' => 'IsKoztartozasmentes',
        'is_megbizhato_adozo' => 'IsMegbizhatoAdozo',
        'has_prohibited_member' => 'HasProhibitedMember',
        'signer_change_in12_months' => 'SignerChangeIn12Months',
        'member_change_in12_months' => 'MemberChangeIn12Months',
        'headquarter_change_in12_months' => 'HeadquarterChangeIn12Months',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'regnumber' => 'setRegnumber',
        'taxnumber' => 'setTaxnumber',
        'name' => 'setName',
        'long_name' => 'setLongName',
        'headquarter' => 'setHeadquarter',
        'status' => 'setStatus',
        'foundation' => 'setFoundation',
        'funds' => 'setFunds',
        'employees' => 'setEmployees',
        'last_turnover' => 'setLastTurnover',
        'main_activity_code' => 'setMainActivityCode',
        'main_activity_description' => 'setMainActivityDescription',
        'rating' => 'setRating',
        'credit_limit' => 'setCreditLimit',
        'industry' => 'setIndustry',
        'type' => 'setType',
        'ksh_number' => 'setKshNumber',
        'eu_taxnumber' => 'setEuTaxnumber',
        'link' => 'setLink',
        'bank_accounts' => 'setBankAccounts',
        'phones' => 'setPhones',
        'emails' => 'setEmails',
        'webpages' => 'setWebpages',
        'negative_info' => 'setNegativeInfo',
        'positive_info' => 'setPositiveInfo',
        'financial_summaries' => 'setFinancialSummaries',
        'signers' => 'setSigners',
        'members' => 'setMembers',
        'auditors' => 'setAuditors',
        'sites' => 'setSites',
        'has_deleted_tax_number' => 'setHasDeletedTaxNumber',
        'has_active_positive_info' => 'setHasActivePositiveInfo',
        'has_active_negative_info' => 'setHasActiveNegativeInfo',
        'is_koztartozasmentes' => 'setIsKoztartozasmentes',
        'is_megbizhato_adozo' => 'setIsMegbizhatoAdozo',
        'has_prohibited_member' => 'setHasProhibitedMember',
        'signer_change_in12_months' => 'setSignerChangeIn12Months',
        'member_change_in12_months' => 'setMemberChangeIn12Months',
        'headquarter_change_in12_months' => 'setHeadquarterChangeIn12Months',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'regnumber' => 'getRegnumber',
        'taxnumber' => 'getTaxnumber',
        'name' => 'getName',
        'long_name' => 'getLongName',
        'headquarter' => 'getHeadquarter',
        'status' => 'getStatus',
        'foundation' => 'getFoundation',
        'funds' => 'getFunds',
        'employees' => 'getEmployees',
        'last_turnover' => 'getLastTurnover',
        'main_activity_code' => 'getMainActivityCode',
        'main_activity_description' => 'getMainActivityDescription',
        'rating' => 'getRating',
        'credit_limit' => 'getCreditLimit',
        'industry' => 'getIndustry',
        'type' => 'getType',
        'ksh_number' => 'getKshNumber',
        'eu_taxnumber' => 'getEuTaxnumber',
        'link' => 'getLink',
        'bank_accounts' => 'getBankAccounts',
        'phones' => 'getPhones',
        'emails' => 'getEmails',
        'webpages' => 'getWebpages',
        'negative_info' => 'getNegativeInfo',
        'positive_info' => 'getPositiveInfo',
        'financial_summaries' => 'getFinancialSummaries',
        'signers' => 'getSigners',
        'members' => 'getMembers',
        'auditors' => 'getAuditors',
        'sites' => 'getSites',
        'has_deleted_tax_number' => 'getHasDeletedTaxNumber',
        'has_active_positive_info' => 'getHasActivePositiveInfo',
        'has_active_negative_info' => 'getHasActiveNegativeInfo',
        'is_koztartozasmentes' => 'getIsKoztartozasmentes',
        'is_megbizhato_adozo' => 'getIsMegbizhatoAdozo',
        'has_prohibited_member' => 'getHasProhibitedMember',
        'signer_change_in12_months' => 'getSignerChangeIn12Months',
        'member_change_in12_months' => 'getMemberChangeIn12Months',
        'headquarter_change_in12_months' => 'getHeadquarterChangeIn12Months',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_MKD = 'Működő';

    public const STATUS_ELJRS_FOLYAMATBAN = 'Eljárás folyamatban';

    public const STATUS_MEGSZNT = 'Megszűnt';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_MKD,
            self::STATUS_ELJRS_FOLYAMATBAN,
            self::STATUS_MEGSZNT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param  mixed[]|null  $data  Associated array of property values
     *                              initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('regnumber', $data ?? [], null);
        $this->setIfExists('taxnumber', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('long_name', $data ?? [], null);
        $this->setIfExists('headquarter', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('foundation', $data ?? [], null);
        $this->setIfExists('funds', $data ?? [], null);
        $this->setIfExists('employees', $data ?? [], null);
        $this->setIfExists('last_turnover', $data ?? [], null);
        $this->setIfExists('main_activity_code', $data ?? [], null);
        $this->setIfExists('main_activity_description', $data ?? [], null);
        $this->setIfExists('rating', $data ?? [], null);
        $this->setIfExists('credit_limit', $data ?? [], null);
        $this->setIfExists('industry', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('ksh_number', $data ?? [], null);
        $this->setIfExists('eu_taxnumber', $data ?? [], null);
        $this->setIfExists('link', $data ?? [], null);
        $this->setIfExists('bank_accounts', $data ?? [], null);
        $this->setIfExists('phones', $data ?? [], null);
        $this->setIfExists('emails', $data ?? [], null);
        $this->setIfExists('webpages', $data ?? [], null);
        $this->setIfExists('negative_info', $data ?? [], null);
        $this->setIfExists('positive_info', $data ?? [], null);
        $this->setIfExists('financial_summaries', $data ?? [], null);
        $this->setIfExists('signers', $data ?? [], null);
        $this->setIfExists('members', $data ?? [], null);
        $this->setIfExists('auditors', $data ?? [], null);
        $this->setIfExists('sites', $data ?? [], null);
        $this->setIfExists('has_deleted_tax_number', $data ?? [], null);
        $this->setIfExists('has_active_positive_info', $data ?? [], null);
        $this->setIfExists('has_active_negative_info', $data ?? [], null);
        $this->setIfExists('is_koztartozasmentes', $data ?? [], null);
        $this->setIfExists('is_megbizhato_adozo', $data ?? [], null);
        $this->setIfExists('has_prohibited_member', $data ?? [], null);
        $this->setIfExists('signer_change_in12_months', $data ?? [], null);
        $this->setIfExists('member_change_in12_months', $data ?? [], null);
        $this->setIfExists('headquarter_change_in12_months', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param  mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets regnumber
     *
     * @return string|null
     */
    public function getRegnumber()
    {
        return $this->container['regnumber'];
    }

    /**
     * Sets regnumber
     *
     * @param  string|null  $regnumber  Cégjegyzékszám
     *
     * @return self
     */
    public function setRegnumber($regnumber)
    {
        if (is_null($regnumber)) {
            throw new \InvalidArgumentException('non-nullable regnumber cannot be null');
        }
        $this->container['regnumber'] = $regnumber;

        return $this;
    }

    /**
     * Gets taxnumber
     *
     * @return string|null
     */
    public function getTaxnumber()
    {
        return $this->container['taxnumber'];
    }

    /**
     * Sets taxnumber
     *
     * @param  string|null  $taxnumber  Adószám
     *
     * @return self
     */
    public function setTaxnumber($taxnumber)
    {
        if (is_null($taxnumber)) {
            throw new \InvalidArgumentException('non-nullable taxnumber cannot be null');
        }
        $this->container['taxnumber'] = $taxnumber;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param  string|null  $name  Rövidített elnevezés
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets long_name
     *
     * @return string|null
     */
    public function getLongName()
    {
        return $this->container['long_name'];
    }

    /**
     * Sets long_name
     *
     * @param  string|null  $long_name  A cég elnevezése
     *
     * @return self
     */
    public function setLongName($long_name)
    {
        if (is_null($long_name)) {
            throw new \InvalidArgumentException('non-nullable long_name cannot be null');
        }
        $this->container['long_name'] = $long_name;

        return $this;
    }

    /**
     * Gets headquarter
     *
     * @return Address|null
     */
    public function getHeadquarter()
    {
        return $this->container['headquarter'];
    }

    /**
     * Sets headquarter
     *
     * @param  Address|null  $headquarter  headquarter
     *
     * @return self
     */
    public function setHeadquarter($headquarter)
    {
        if (is_null($headquarter)) {
            throw new \InvalidArgumentException('non-nullable headquarter cannot be null');
        }
        $this->container['headquarter'] = $headquarter;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param  string|null  $status  Állapot
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets foundation
     *
     * @return \DateTime|null
     */
    public function getFoundation()
    {
        return $this->container['foundation'];
    }

    /**
     * Sets foundation
     *
     * @param  \DateTime|null  $foundation  Alapítás dátuma
     *
     * @return self
     */
    public function setFoundation($foundation)
    {
        if (is_null($foundation)) {
            throw new \InvalidArgumentException('non-nullable foundation cannot be null');
        }
        $this->container['foundation'] = $foundation;

        return $this;
    }

    /**
     * Gets funds
     *
     * @return string|null
     */
    public function getFunds()
    {
        return $this->container['funds'];
    }

    /**
     * Sets funds
     *
     * @param  string|null  $funds  Alaptőke
     *
     * @return self
     */
    public function setFunds($funds)
    {
        if (is_null($funds)) {
            throw new \InvalidArgumentException('non-nullable funds cannot be null');
        }
        $this->container['funds'] = $funds;

        return $this;
    }

    /**
     * Gets employees
     *
     * @return int|null
     */
    public function getEmployees()
    {
        return $this->container['employees'];
    }

    /**
     * Sets employees
     *
     * @param  int|null  $employees  Alkalmazottak száma
     *
     * @return self
     */
    public function setEmployees($employees)
    {
        if (is_null($employees)) {
            throw new \InvalidArgumentException('non-nullable employees cannot be null');
        }
        $this->container['employees'] = $employees;

        return $this;
    }

    /**
     * Gets last_turnover
     *
     * @return int|null
     */
    public function getLastTurnover()
    {
        return $this->container['last_turnover'];
    }

    /**
     * Sets last_turnover
     *
     * @param  int|null  $last_turnover  Utolsó árbevétel
     *
     * @return self
     */
    public function setLastTurnover($last_turnover)
    {
        if (is_null($last_turnover)) {
            throw new \InvalidArgumentException('non-nullable last_turnover cannot be null');
        }
        $this->container['last_turnover'] = $last_turnover;

        return $this;
    }

    /**
     * Gets main_activity_code
     *
     * @return string|null
     */
    public function getMainActivityCode()
    {
        return $this->container['main_activity_code'];
    }

    /**
     * Sets main_activity_code
     *
     * @param  string|null  $main_activity_code  Főtevékenység kódja
     *
     * @return self
     */
    public function setMainActivityCode($main_activity_code)
    {
        if (is_null($main_activity_code)) {
            throw new \InvalidArgumentException('non-nullable main_activity_code cannot be null');
        }
        $this->container['main_activity_code'] = $main_activity_code;

        return $this;
    }

    /**
     * Gets main_activity_description
     *
     * @return string|null
     */
    public function getMainActivityDescription()
    {
        return $this->container['main_activity_description'];
    }

    /**
     * Sets main_activity_description
     *
     * @param  string|null  $main_activity_description  Főtevékenység neve
     *
     * @return self
     */
    public function setMainActivityDescription($main_activity_description)
    {
        if (is_null($main_activity_description)) {
            throw new \InvalidArgumentException('non-nullable main_activity_description cannot be null');
        }
        $this->container['main_activity_description'] = $main_activity_description;

        return $this;
    }

    /**
     * Gets rating
     *
     * @return int|null
     */
    public function getRating()
    {
        return $this->container['rating'];
    }

    /**
     * Sets rating
     *
     * @param  int|null  $rating  Besorolás
     *
     * @return self
     */
    public function setRating($rating)
    {
        if (is_null($rating)) {
            throw new \InvalidArgumentException('non-nullable rating cannot be null');
        }
        $this->container['rating'] = $rating;

        return $this;
    }

    /**
     * Gets credit_limit
     *
     * @return int|null
     */
    public function getCreditLimit()
    {
        return $this->container['credit_limit'];
    }

    /**
     * Sets credit_limit
     *
     * @param  int|null  $credit_limit  Hitelképesség
     *
     * @return self
     */
    public function setCreditLimit($credit_limit)
    {
        if (is_null($credit_limit)) {
            throw new \InvalidArgumentException('non-nullable credit_limit cannot be null');
        }
        $this->container['credit_limit'] = $credit_limit;

        return $this;
    }

    /**
     * Gets industry
     *
     * @return string|null
     */
    public function getIndustry()
    {
        return $this->container['industry'];
    }

    /**
     * Sets industry
     *
     * @param  string|null  $industry  Iparág
     *
     * @return self
     */
    public function setIndustry($industry)
    {
        if (is_null($industry)) {
            throw new \InvalidArgumentException('non-nullable industry cannot be null');
        }
        $this->container['industry'] = $industry;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param  string|null  $type  Gazdálkodási forma
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets ksh_number
     *
     * @return string|null
     */
    public function getKshNumber()
    {
        return $this->container['ksh_number'];
    }

    /**
     * Sets ksh_number
     *
     * @param  string|null  $ksh_number  KSH szám
     *
     * @return self
     */
    public function setKshNumber($ksh_number)
    {
        if (is_null($ksh_number)) {
            throw new \InvalidArgumentException('non-nullable ksh_number cannot be null');
        }
        $this->container['ksh_number'] = $ksh_number;

        return $this;
    }

    /**
     * Gets eu_taxnumber
     *
     * @return string|null
     */
    public function getEuTaxnumber()
    {
        return $this->container['eu_taxnumber'];
    }

    /**
     * Sets eu_taxnumber
     *
     * @param  string|null  $eu_taxnumber  EU adószám
     *
     * @return self
     */
    public function setEuTaxnumber($eu_taxnumber)
    {
        if (is_null($eu_taxnumber)) {
            throw new \InvalidArgumentException('non-nullable eu_taxnumber cannot be null');
        }
        $this->container['eu_taxnumber'] = $eu_taxnumber;

        return $this;
    }

    /**
     * Gets link
     *
     * @return string|null
     */
    public function getLink()
    {
        return $this->container['link'];
    }

    /**
     * Sets link
     *
     * @param  string|null  $link  Credit Online adatlapra mutató link
     *
     * @return self
     */
    public function setLink($link)
    {
        if (is_null($link)) {
            throw new \InvalidArgumentException('non-nullable link cannot be null');
        }
        $this->container['link'] = $link;

        return $this;
    }

    /**
     * Gets bank_accounts
     *
     * @return string[]|null
     */
    public function getBankAccounts()
    {
        return $this->container['bank_accounts'];
    }

    /**
     * Sets bank_accounts
     *
     * @param  string[]|null  $bank_accounts  Bankszámlák
     *
     * @return self
     */
    public function setBankAccounts($bank_accounts)
    {
        if (is_null($bank_accounts)) {
            throw new \InvalidArgumentException('non-nullable bank_accounts cannot be null');
        }
        $this->container['bank_accounts'] = $bank_accounts;

        return $this;
    }

    /**
     * Gets phones
     *
     * @return string[]|null
     */
    public function getPhones()
    {
        return $this->container['phones'];
    }

    /**
     * Sets phones
     *
     * @param  string[]|null  $phones  Telefonszámok (max. 3 db)
     *
     * @return self
     */
    public function setPhones($phones)
    {
        if (is_null($phones)) {
            throw new \InvalidArgumentException('non-nullable phones cannot be null');
        }
        $this->container['phones'] = $phones;

        return $this;
    }

    /**
     * Gets emails
     *
     * @return string[]|null
     */
    public function getEmails()
    {
        return $this->container['emails'];
    }

    /**
     * Sets emails
     *
     * @param  string[]|null  $emails  Email címek (max. 3 db)
     *
     * @return self
     */
    public function setEmails($emails)
    {
        if (is_null($emails)) {
            throw new \InvalidArgumentException('non-nullable emails cannot be null');
        }
        $this->container['emails'] = $emails;

        return $this;
    }

    /**
     * Gets webpages
     *
     * @return string[]|null
     */
    public function getWebpages()
    {
        return $this->container['webpages'];
    }

    /**
     * Sets webpages
     *
     * @param  string[]|null  $webpages  Weblapok (max. 3 db)
     *
     * @return self
     */
    public function setWebpages($webpages)
    {
        if (is_null($webpages)) {
            throw new \InvalidArgumentException('non-nullable webpages cannot be null');
        }
        $this->container['webpages'] = $webpages;

        return $this;
    }

    /**
     * Gets negative_info
     *
     * @return NegativeInfo[]|null
     */
    public function getNegativeInfo()
    {
        return $this->container['negative_info'];
    }

    /**
     * Sets negative_info
     *
     * @param  NegativeInfo[]|null  $negative_info  Negatív információk
     *
     * @return self
     */
    public function setNegativeInfo($negative_info)
    {
        if (is_null($negative_info)) {
            throw new \InvalidArgumentException('non-nullable negative_info cannot be null');
        }
        $this->container['negative_info'] = $negative_info;

        return $this;
    }

    /**
     * Gets positive_info
     *
     * @return PositiveInfo[]|null
     */
    public function getPositiveInfo()
    {
        return $this->container['positive_info'];
    }

    /**
     * Sets positive_info
     *
     * @param  PositiveInfo[]|null  $positive_info  Pozitív információk
     *
     * @return self
     */
    public function setPositiveInfo($positive_info)
    {
        if (is_null($positive_info)) {
            throw new \InvalidArgumentException('non-nullable positive_info cannot be null');
        }
        $this->container['positive_info'] = $positive_info;

        return $this;
    }

    /**
     * Gets financial_summaries
     *
     * @return FinancialSummary[]|null
     */
    public function getFinancialSummaries()
    {
        return $this->container['financial_summaries'];
    }

    /**
     * Sets financial_summaries
     *
     * @param  FinancialSummary[]|null  $financial_summaries  Pénzügyi adatok (utolsó 3 év)
     *
     * @return self
     */
    public function setFinancialSummaries($financial_summaries)
    {
        if (is_null($financial_summaries)) {
            throw new \InvalidArgumentException('non-nullable financial_summaries cannot be null');
        }
        $this->container['financial_summaries'] = $financial_summaries;

        return $this;
    }

    /**
     * Gets signers
     *
     * @return Signer[]|null
     */
    public function getSigners()
    {
        return $this->container['signers'];
    }

    /**
     * Sets signers
     *
     * @param  Signer[]|null  $signers  Cégjegyzésre jogosultak
     *
     * @return self
     */
    public function setSigners($signers)
    {
        if (is_null($signers)) {
            throw new \InvalidArgumentException('non-nullable signers cannot be null');
        }
        $this->container['signers'] = $signers;

        return $this;
    }

    /**
     * Gets members
     *
     * @return Member[]|null
     */
    public function getMembers()
    {
        return $this->container['members'];
    }

    /**
     * Sets members
     *
     * @param  Member[]|null  $members  Tulajdonosok
     *
     * @return self
     */
    public function setMembers($members)
    {
        if (is_null($members)) {
            throw new \InvalidArgumentException('non-nullable members cannot be null');
        }
        $this->container['members'] = $members;

        return $this;
    }

    /**
     * Gets auditors
     *
     * @return Auditor[]|null
     */
    public function getAuditors()
    {
        return $this->container['auditors'];
    }

    /**
     * Sets auditors
     *
     * @param  Auditor[]|null  $auditors  Könyvvizsgálók
     *
     * @return self
     */
    public function setAuditors($auditors)
    {
        if (is_null($auditors)) {
            throw new \InvalidArgumentException('non-nullable auditors cannot be null');
        }
        $this->container['auditors'] = $auditors;

        return $this;
    }

    /**
     * Gets sites
     *
     * @return Address[]|null
     */
    public function getSites()
    {
        return $this->container['sites'];
    }

    /**
     * Sets sites
     *
     * @param  Address[]|null  $sites  Telephelyek
     *
     * @return self
     */
    public function setSites($sites)
    {
        if (is_null($sites)) {
            throw new \InvalidArgumentException('non-nullable sites cannot be null');
        }
        $this->container['sites'] = $sites;

        return $this;
    }

    /**
     * Gets has_deleted_tax_number
     *
     * @return bool|null
     */
    public function getHasDeletedTaxNumber()
    {
        return $this->container['has_deleted_tax_number'];
    }

    /**
     * Sets has_deleted_tax_number
     *
     * @param  bool|null  $has_deleted_tax_number  Az adószáma törölt-e?
     *
     * @return self
     */
    public function setHasDeletedTaxNumber($has_deleted_tax_number)
    {
        if (is_null($has_deleted_tax_number)) {
            throw new \InvalidArgumentException('non-nullable has_deleted_tax_number cannot be null');
        }
        $this->container['has_deleted_tax_number'] = $has_deleted_tax_number;

        return $this;
    }

    /**
     * Gets has_active_positive_info
     *
     * @return bool|null
     */
    public function getHasActivePositiveInfo()
    {
        return $this->container['has_active_positive_info'];
    }

    /**
     * Sets has_active_positive_info
     *
     * @param  bool|null  $has_active_positive_info  Hatályos pozitív infó van-e a cég ellen?
     *
     * @return self
     */
    public function setHasActivePositiveInfo($has_active_positive_info)
    {
        if (is_null($has_active_positive_info)) {
            throw new \InvalidArgumentException('non-nullable has_active_positive_info cannot be null');
        }
        $this->container['has_active_positive_info'] = $has_active_positive_info;

        return $this;
    }

    /**
     * Gets has_active_negative_info
     *
     * @return bool|null
     */
    public function getHasActiveNegativeInfo()
    {
        return $this->container['has_active_negative_info'];
    }

    /**
     * Sets has_active_negative_info
     *
     * @param  bool|null  $has_active_negative_info  Hatályos negatív infó van-e a cég ellen?
     *
     * @return self
     */
    public function setHasActiveNegativeInfo($has_active_negative_info)
    {
        if (is_null($has_active_negative_info)) {
            throw new \InvalidArgumentException('non-nullable has_active_negative_info cannot be null');
        }
        $this->container['has_active_negative_info'] = $has_active_negative_info;

        return $this;
    }

    /**
     * Gets is_koztartozasmentes
     *
     * @return bool|null
     */
    public function getIsKoztartozasmentes()
    {
        return $this->container['is_koztartozasmentes'];
    }

    /**
     * Sets is_koztartozasmentes
     *
     * @param  bool|null  $is_koztartozasmentes  Szerepel-e a köztartozásmentes adózók listáján?
     *
     * @return self
     */
    public function setIsKoztartozasmentes($is_koztartozasmentes)
    {
        if (is_null($is_koztartozasmentes)) {
            throw new \InvalidArgumentException('non-nullable is_koztartozasmentes cannot be null');
        }
        $this->container['is_koztartozasmentes'] = $is_koztartozasmentes;

        return $this;
    }

    /**
     * Gets is_megbizhato_adozo
     *
     * @return bool|null
     */
    public function getIsMegbizhatoAdozo()
    {
        return $this->container['is_megbizhato_adozo'];
    }

    /**
     * Sets is_megbizhato_adozo
     *
     * @param  bool|null  $is_megbizhato_adozo  Szerepel-e a megbízható adózók listáján?
     *
     * @return self
     */
    public function setIsMegbizhatoAdozo($is_megbizhato_adozo)
    {
        if (is_null($is_megbizhato_adozo)) {
            throw new \InvalidArgumentException('non-nullable is_megbizhato_adozo cannot be null');
        }
        $this->container['is_megbizhato_adozo'] = $is_megbizhato_adozo;

        return $this;
    }

    /**
     * Gets has_prohibited_member
     *
     * @return bool|null
     */
    public function getHasProhibitedMember()
    {
        return $this->container['has_prohibited_member'];
    }

    /**
     * Sets has_prohibited_member
     *
     * @param  bool|null  $has_prohibited_member  Cégvezetéstől eltiltott személy található?
     *
     * @return self
     */
    public function setHasProhibitedMember($has_prohibited_member)
    {
        if (is_null($has_prohibited_member)) {
            throw new \InvalidArgumentException('non-nullable has_prohibited_member cannot be null');
        }
        $this->container['has_prohibited_member'] = $has_prohibited_member;

        return $this;
    }

    /**
     * Gets signer_change_in12_months
     *
     * @return bool|null
     */
    public function getSignerChangeIn12Months()
    {
        return $this->container['signer_change_in12_months'];
    }

    /**
     * Sets signer_change_in12_months
     *
     * @param  bool|null  $signer_change_in12_months  Cégjegyzésre jogosult változás az elmúlt 12 hónapban?
     *
     * @return self
     */
    public function setSignerChangeIn12Months($signer_change_in12_months)
    {
        if (is_null($signer_change_in12_months)) {
            throw new \InvalidArgumentException('non-nullable signer_change_in12_months cannot be null');
        }
        $this->container['signer_change_in12_months'] = $signer_change_in12_months;

        return $this;
    }

    /**
     * Gets member_change_in12_months
     *
     * @return bool|null
     */
    public function getMemberChangeIn12Months()
    {
        return $this->container['member_change_in12_months'];
    }

    /**
     * Sets member_change_in12_months
     *
     * @param  bool|null  $member_change_in12_months  Tulajdonos jogosult változás az elmúlt 12 hónapban?
     *
     * @return self
     */
    public function setMemberChangeIn12Months($member_change_in12_months)
    {
        if (is_null($member_change_in12_months)) {
            throw new \InvalidArgumentException('non-nullable member_change_in12_months cannot be null');
        }
        $this->container['member_change_in12_months'] = $member_change_in12_months;

        return $this;
    }

    /**
     * Gets headquarter_change_in12_months
     *
     * @return bool|null
     */
    public function getHeadquarterChangeIn12Months()
    {
        return $this->container['headquarter_change_in12_months'];
    }

    /**
     * Sets headquarter_change_in12_months
     *
     * @param  bool|null  $headquarter_change_in12_months  Székhely jogosult változás az elmúlt 12 hónapban?
     *
     * @return self
     */
    public function setHeadquarterChangeIn12Months($headquarter_change_in12_months)
    {
        if (is_null($headquarter_change_in12_months)) {
            throw new \InvalidArgumentException('non-nullable headquarter_change_in12_months cannot be null');
        }
        $this->container['headquarter_change_in12_months'] = $headquarter_change_in12_months;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  int|string  $offset  Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  int|null  $offset  Offset
     * @param  mixed  $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
