<?php
/**
 * FinancialSummary
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OmisaiCreditOnline
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Credit Online API
 *
 * A Token hívás segítségével generált egyedi tokennel hívható a többi metódus. Az egyes funkciók a dokumentációban a \"Try it out\" gomb megnyomásával online is kipróbálhatóak.
 *
 * The version of the OpenAPI document: 3
 * Contact: antolik.laszlo@creditcontrol.hu
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Omisai\CreditOnline\Model;

use \ArrayAccess;
use \OmisaiCreditOnline\ObjectSerializer;

/**
 * FinancialSummary Class Doc Comment
 *
 * @category Class
 * @package  OmisaiCreditOnline
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FinancialSummary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FinancialSummary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'year' => 'int',
        'total_sales' => 'int',
        'income_from_operations' => 'int',
        'profit_after_taxation' => 'int',
        'subscribed_capital' => 'int',
        'shareholders_equity' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'year' => null,
        'total_sales' => null,
        'income_from_operations' => null,
        'profit_after_taxation' => null,
        'subscribed_capital' => null,
        'shareholders_equity' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'year' => false,
        'total_sales' => false,
        'income_from_operations' => false,
        'profit_after_taxation' => false,
        'subscribed_capital' => false,
        'shareholders_equity' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'year' => 'Year',
        'total_sales' => 'TotalSales',
        'income_from_operations' => 'IncomeFromOperations',
        'profit_after_taxation' => 'ProfitAfterTaxation',
        'subscribed_capital' => 'SubscribedCapital',
        'shareholders_equity' => 'ShareholdersEquity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'year' => 'setYear',
        'total_sales' => 'setTotalSales',
        'income_from_operations' => 'setIncomeFromOperations',
        'profit_after_taxation' => 'setProfitAfterTaxation',
        'subscribed_capital' => 'setSubscribedCapital',
        'shareholders_equity' => 'setShareholdersEquity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'year' => 'getYear',
        'total_sales' => 'getTotalSales',
        'income_from_operations' => 'getIncomeFromOperations',
        'profit_after_taxation' => 'getProfitAfterTaxation',
        'subscribed_capital' => 'getSubscribedCapital',
        'shareholders_equity' => 'getShareholdersEquity'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('year', $data ?? [], null);
        $this->setIfExists('total_sales', $data ?? [], null);
        $this->setIfExists('income_from_operations', $data ?? [], null);
        $this->setIfExists('profit_after_taxation', $data ?? [], null);
        $this->setIfExists('subscribed_capital', $data ?? [], null);
        $this->setIfExists('shareholders_equity', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets year
     *
     * @return int|null
     */
    public function getYear()
    {
        return $this->container['year'];
    }

    /**
     * Sets year
     *
     * @param int|null $year Év
     *
     * @return self
     */
    public function setYear($year)
    {
        if (is_null($year)) {
            throw new \InvalidArgumentException('non-nullable year cannot be null');
        }
        $this->container['year'] = $year;

        return $this;
    }

    /**
     * Gets total_sales
     *
     * @return int|null
     */
    public function getTotalSales()
    {
        return $this->container['total_sales'];
    }

    /**
     * Sets total_sales
     *
     * @param int|null $total_sales Értékesítés nettó árbevétele
     *
     * @return self
     */
    public function setTotalSales($total_sales)
    {
        if (is_null($total_sales)) {
            throw new \InvalidArgumentException('non-nullable total_sales cannot be null');
        }
        $this->container['total_sales'] = $total_sales;

        return $this;
    }

    /**
     * Gets income_from_operations
     *
     * @return int|null
     */
    public function getIncomeFromOperations()
    {
        return $this->container['income_from_operations'];
    }

    /**
     * Sets income_from_operations
     *
     * @param int|null $income_from_operations Üzemi tevékenység eredménye
     *
     * @return self
     */
    public function setIncomeFromOperations($income_from_operations)
    {
        if (is_null($income_from_operations)) {
            throw new \InvalidArgumentException('non-nullable income_from_operations cannot be null');
        }
        $this->container['income_from_operations'] = $income_from_operations;

        return $this;
    }

    /**
     * Gets profit_after_taxation
     *
     * @return int|null
     */
    public function getProfitAfterTaxation()
    {
        return $this->container['profit_after_taxation'];
    }

    /**
     * Sets profit_after_taxation
     *
     * @param int|null $profit_after_taxation Adózott eredmény
     *
     * @return self
     */
    public function setProfitAfterTaxation($profit_after_taxation)
    {
        if (is_null($profit_after_taxation)) {
            throw new \InvalidArgumentException('non-nullable profit_after_taxation cannot be null');
        }
        $this->container['profit_after_taxation'] = $profit_after_taxation;

        return $this;
    }

    /**
     * Gets subscribed_capital
     *
     * @return int|null
     */
    public function getSubscribedCapital()
    {
        return $this->container['subscribed_capital'];
    }

    /**
     * Sets subscribed_capital
     *
     * @param int|null $subscribed_capital Jegyzett tőke
     *
     * @return self
     */
    public function setSubscribedCapital($subscribed_capital)
    {
        if (is_null($subscribed_capital)) {
            throw new \InvalidArgumentException('non-nullable subscribed_capital cannot be null');
        }
        $this->container['subscribed_capital'] = $subscribed_capital;

        return $this;
    }

    /**
     * Gets shareholders_equity
     *
     * @return int|null
     */
    public function getShareholdersEquity()
    {
        return $this->container['shareholders_equity'];
    }

    /**
     * Sets shareholders_equity
     *
     * @param int|null $shareholders_equity Saját tőke
     *
     * @return self
     */
    public function setShareholdersEquity($shareholders_equity)
    {
        if (is_null($shareholders_equity)) {
            throw new \InvalidArgumentException('non-nullable shareholders_equity cannot be null');
        }
        $this->container['shareholders_equity'] = $shareholders_equity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


